ARCH := -mcpu=arm7tdmi
WARNS := -Wall
CFLAGS := -O2 $(WARNS) -fdiagnostics-show-option -march=armv4t -Wno-switch -Wno-multichar -ffast-math $(ARCH) -mtune=arm7tdmi -marm -mlong-calls -flto ${CFLAGS}
LDFLAGS = -nostartfiles -Tlnkscript
DEBUG ?= false

objs := lib/crt0.o lib/font.o lib/input.o lib/halt.o lib/gen/patterns_packed.o lib/gen/patterns_rle.o

# for some reason main.c has to be the last argument?
a.out: $(objs) main.c include/*.h
	$(CC) $(CFLAGS) $(LDFLAGS) $(objs) main.c

test: a.out
	mgba-qt -3 a.out

# generated by re2c
gen/scanners/%.c: misc/%.r2c
	mkdir -p gen/scanners
	re2c $< -o $@

# generated by c code
gen/%.c: build/gen_patterns all/*
	mkdir -p gen
	./build/gen_patterns

lib/scanners/%.o: gen/scanners/%.c
	mkdir -p lib/scanners
	clang $(WARNS) -c -O1 -g -o $@ $^

lib/gen/%.o: gen/%.c
	mkdir -p lib/gen
	$(CC) $(CFLAGS) -s -c -o $@ $^

build/gen_patterns: lib/scanners/rle_header.o misc/gen_patterns.c
	# -fsanitize=address -fno-omit-frame-pointer
	mkdir -p build
	clang $(WARNS) -Werror -O2 -o $@ $^

lib/%.o: src/%.c
	mkdir -p lib
	$(CC) $(CFLAGS) -c -o $@ $<

lib/%.o: src/%.s
	mkdir -p lib
	$(AS) -o $@ $< $(ASFLAGS)

clean:
	rm -rf *.gba lib *.out *.elf *.sav
	rm -rf build gen

a.gba: a.out
	$(OBJCOPY) -O binary a.out a.gba

life.gba: a.gba
	./ht.pl -n "Game of Life" -clo life.gba a.gba
